### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by warpech** [Starcounter/DisplayAppTitle#4]
This app should be released. Remaining steps:

- [x] Merge branch [displayapptitle](https://github.com/StarcounterApps/Simplified/tree/displayapptitle) in Simplified
- [x] Check if information in README.md is enough to understand what is this app for and how to use it
- [x] Release version 1.0.0 of this app and put it to Warehouse

**Comment by PatrykSzwer** [comment]
Branch [displayapptitle](https://github.com/StarcounterApps/Simplified/tree/displayapptitle) war merged.

**Comment by PatrykSzwer** [comment]
>  Check if information in README.md is enough to understand what is this app for and how to use it

I think that README.md right now doesn't explain enough, what this app is for/what can it be used for. It also lack of common sections that We have in other apps (Licence, contribution/development instructions).

**Comment by PatrykSzwer** [comment]
Version 1.0.0 was released and added to Warehouse.

**Comment by warpech** [comment]
@PatrykSzwer please review PR #6

**Comment by warpech** [comment]
All points are done. Closing

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/DisplayAppTitle/releases/tag/1.1.0
- published in the App Warehouse
