### ISSUE TITLE
Migrate to Polymer 2

### ISSUE THREAD

**Issue by alshakero** [Starcounter/DisplayAppTitle#7]

**Comment by alshakero** [comment]
This is waiting for https://github.com/Juicy/juicy-color-picker/pull/7 since it depends on it.

**Comment by alshakero** [comment]
PR https://github.com/Starcounter/DisplayAppTitle/issues/7

**Comment by warpech** [comment]
Done in PR #7.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/DisplayAppTitle/releases/tag/1.1.0
- published in the App Warehouse
